// PDM Runbook - Ceremony Data
const CEREMONIES_DATA = {
  personas: [
    { id: "pdm", name: "Portfolio Delivery Manager", shortName: "PDM", active: true },
    { id: "adm", name: "Agile Delivery Manager", shortName: "ADM", active: false },
    { id: "po", name: "Product Owner", shortName: "PO", active: false },
    { id: "pl", name: "Portfolio Lead", shortName: "PL", active: false }
  ],

  sprints: [
    { id: "sprint-1", name: "Sprint 1", shortName: "S1", position: 1 },
    { id: "sprint-2", name: "Sprint 2", shortName: "S2", position: 2 },
    { id: "sprint-3", name: "Sprint 3", shortName: "S3", position: 3 },
    { id: "sprint-4", name: "Sprint 4", shortName: "S4", position: 4 },
    { id: "sprint-5", name: "Sprint 5", shortName: "S5", position: 5 },
    { id: "sprint-6-ia", name: "Sprint 6 (I&A)", shortName: "I&A", position: 6 }
  ],

  categories: [
    { id: "ti-planning", name: "TI Planning", color: "#500778", icon: "📋" },
    { id: "delivery", name: "Delivery", color: "#0097A9", icon: "🚀" },
    { id: "finances", name: "Finances", color: "#E87722", icon: "💰" },
    { id: "lbcs-ddtc", name: "LBCs & DDTC", color: "#8C1515", icon: "📊" }
  ],

  activityGroups: [
    { id: "CIO", name: "CIO LT Commitments" },
    { id: "TIP", name: "TI Planning" },
    { id: "IAD", name: "Inspect & Adapt" },
    { id: "PV", name: "Portfolio Vision" },
    { id: "VoV", name: "Vision of Visions" },
    { id: "EDS", name: "Extended Delivery Sync" },
    { id: "DHPR", name: "Delivery Health & Portfolio Review" },
    { id: "RM", name: "Resource Meeting" },
    { id: "JAM", name: "Jamboree" },
    { id: "SD", name: "Showcase Demo" },
    { id: "MFKT", name: "Monthly Finance Review" },
    { id: "DDTC", name: "Digital Delivery & Transformation Committee" },
    { id: "DDTCR", name: "Pre-DDTC (Risks)" }
  ],

  ceremonies: [
    // ========== TI PLANNING ==========
    {
      id: "cio-lt-commitments",
      name: "CIO LT – TI Commitments",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "CIO",
      sprints: ["sprint-1"],
      description: "Playback key planned Outcomes, key risks, and highlight practice and resource challenges.",
      outcome: "Confirmed alignment across the portfolios, agreed key priorities and dependency resolutions, and identified actions required to address outstanding risks.",
      whoAttends: "CIO LT, PDMs and LPG",
      keyResponsibilities: "",
      relatedArtefact: "cio-lt-prep"
    },
    {
      id: "cio-lt-prep",
      name: "CIO LT - TI Commitment Prep",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "CIO",
      sprints: ["sprint-1"],
      description: "The PDM gathers all committed outcomes, highlights the key risks and resource challenges in the CIO LT Playback Deck.",
      outcome: "The CIO LT Playback Deck is updated.",
      whoAttends: "Change Portfolio Manager",
      keyResponsibilities: "",
      relatedMeeting: "cio-lt-commitments"
    },
    {
      id: "ti-planning-meeting",
      name: "TI Planning",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "TIP",
      sprints: ["sprint-6-ia"],
      description: "A quarterly, collaborative event that serves as the heartbeat of agile working at UCL, aligning all the teams to a shared mission and vision. This event includes stakeholders from outside ISD, ISD Leadership and all Product/Platform Team members and occurs within the Innovation and Planning (IP) Iteration.",
      outcome: "Aligned iteration plans and objectives across all teams, with clear priorities, dependencies identified, and commitment to delivering the Termly Increment goals.",
      whoAttends: "Product and Platform Teams, Product and Platform Owners, Change Portfolio Leadership Teams, Lean Portfolio Group, Centre of Excellence, ISD Leadership, Relevant key stakeholders external to ISD",
      keyResponsibilities: "Coordinates and facilitates the Change Portfolio TI event\nEnsures the Change Portfolio Programme board is updated\nEnsures plans are realistic / dependencies are tracked and resolved\nRisks are ROAMed",
      relatedArtefact: null
    },
    {
      id: "arc-room-booking",
      name: "ARC TI Planning: Room Booking & Desk Negotiation",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "TIP",
      sprints: ["sprint-1"],
      description: "The ARC PDM to ensure that all required rooms and desks are booked through Estates for ARC TI Planning, if it takes place outside their usual working day (Tuesday).",
      outcome: "All required rooms and desks are booked.",
      whoAttends: "ARC PDM, Estates Bidborough Building Manager",
      keyResponsibilities: "",
      relatedMeeting: "ti-planning-meeting"
    },
    {
      id: "ti-planning-floor-plan",
      name: "TI Planning Floor Plan",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "TIP",
      sprints: ["sprint-3"],
      description: "The purpose of this activity is for the PDM to review the floor plan with their teams, ensure that all AV equipment is assigned, and confirm that each team has been allocated an appropriate space.",
      outcome: "All AV equipment is assigned, and each team has been allocated an appropriate space.",
      whoAttends: "Portfolio Delivery Manager, Agile Delivery Manager",
      keyResponsibilities: "",
      relatedMeeting: "ti-planning-meeting"
    },
    {
      id: "ti-planning-agenda-keynote",
      name: "Plan TI Planning Agenda & Keynote",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "TIP",
      sprints: ["sprint-3"],
      description: "The PDM prepares and communicates the TI Planning agenda and keynote, ensuring alignment on the portfolio-specific agenda and overall plan, and that all teams are informed, aligned, and ready to participate effectively.",
      outcome: "Clear, communicated TI Planning agenda and keynote, with all teams aligned, informed, and prepared to participate in the session.",
      whoAttends: "Change Portfolio Delivery Manager, All teams within the Change Portfolio",
      keyResponsibilities: "",
      relatedMeeting: "ti-planning-meeting"
    },
    {
      id: "ti-planning-party-prep",
      name: "TI Planning Party Prep",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "TIP",
      sprints: ["sprint-4"],
      description: "For each TI Planning event, a different Portfolio Delivery Manager is assigned to coordinate the TI Planning social event. The purpose of this activity is to ensure the PDM plans and manages all required arrangements in advance, including allocating time in their diary to deliver the event successfully.",
      outcome: "The social event budget is confirmed with the ITTPD Director, risk assessment submitted and approved, snacks, food and drinks are arranged, the designated area is clean at the end of the event.",
      whoAttends: "Change Portfolio Delivery Manager",
      keyResponsibilities: "Confirm the social event budget with the ITPPD Director\nArrange snacks, food, and drinks\nComplete the event risk assessment before the event\nEnsure the designated area is clean and tidy at the end of the event",
      relatedMeeting: "ti-planning-party"
    },
    {
      id: "ti-planning-party",
      name: "TI Planning Party",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "TIP",
      sprints: ["sprint-6-ia"],
      description: "The assigned PDM coordinates the TI Planning social event, ensuring invites are sent, logistics are organised, and the event runs smoothly, with the designated area left clean afterwards.",
      outcome: "A well-organised and smoothly executed social event, with all arrangements managed, attendees engaged, and the venue left in good order.",
      whoAttends: "ISD, and various institutional stakeholders",
      keyResponsibilities: "Confirm with the ITPPD Director the overall budget for the social\nOrder snacks, food, drinks\nComplete the Risk Assessment for the social\nMake sure that the area that is assigned for the social is clean at the end",
      relatedArtefact: "ti-planning-party-prep"
    },
    {
      id: "day-1-management-review",
      name: "Day 1 Management Review",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "TIP",
      sprints: ["sprint-6-ia"],
      description: "To review alignment across all portfolios, assess risks, dependencies and capacity, and confirm priorities and delivery confidence ahead of the start of the TI.",
      outcome: "Confirmed alignment across the portfolios, agreed key priorities and dependency resolutions, and identified actions required to address outstanding risks.",
      whoAttends: "CIO, Director of Delivery, Director of Strategic Change, Portfolio Leadership Groups (PDMs, Portfolio Owners, Portfolio Leads, Portfolio BAs, Portfolio Architects) and Capability Leads",
      keyResponsibilities: "",
      relatedArtefact: null
    },
    {
      id: "day-2-management-review",
      name: "Day 2 Management Review",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "TIP",
      sprints: ["sprint-6-ia"],
      description: "To review alignment across all portfolios, assess risks, dependencies and capacity, and confirm priorities and delivery confidence ahead of the start of the TI.",
      outcome: "Confirmed alignment across the portfolios, agreed key priorities and dependency resolutions, and identified actions required to address outstanding risks.",
      whoAttends: "CIO, Director of Delivery, Director of Strategic Change, Portfolio Leadership Groups (PDMs, Portfolio Owners, Portfolio Leads, Portfolio BAs, Portfolio Architects) and Capability Leads",
      keyResponsibilities: "Talk with their teams about all committed, stretched and uncommitted outcomes\nMake sure that their Change Portfolio has updated the required slides/spreadsheets",
      relatedArtefact: "present-outcomes-day2"
    },
    {
      id: "present-outcomes-day2",
      name: "Present Outcomes on TI Planning Day 2",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "TIP",
      sprints: ["sprint-6-ia"],
      description: "This session is intended to provide all committed outcomes/objectives per portfolio, any stretched outcomes or any outcomes that the portfolio won't be able to deliver and provide reasons why they won't be able to deliver it.",
      outcome: "All committed, stretched and uncommitted outcomes are presented and documented.",
      whoAttends: "ITTPD Director, Change Portfolio Owner, Portfolio Delivery Manager, Change Portfolio Lead, Head of LPG",
      keyResponsibilities: "Talk with their teams about all committed, stretched and uncommitted outcomes\nMake sure that their Change Portfolio has updated the required slides/spreadsheets",
      relatedMeeting: "day-2-management-review"
    },
    {
      id: "ti-risks-dependencies",
      name: "TI Risks & Dependencies",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "TIP",
      sprints: ["sprint-5"],
      description: "The purpose of this quarterly activity is to provide a cross-portfolio view of key risks, dependencies, and planned initiatives identified during Term Increment (TI) Planning. It enables portfolios to share a high-level view of the work they intend to deliver in the upcoming term and ensures that interdependencies are identified, communicated, and incorporated into planning activities. The aim is to build shared visibility across portfolios, align priorities, and surface key risks and dependencies early to support effective delivery planning and coordination.",
      outcome: "All risks and cross-portfolio dependencies are outlined.",
      whoAttends: "ITTPD Director, Change Portfolio Owner, Portfolio Delivery Manager, Change Portfolio Lead, Lean Portfolio Group",
      keyResponsibilities: "Ensure that all identified cross-portfolio risks and dependencies are documented and shared with relevant portfolios and stakeholders\nEnsure that delivery teams are aware of dependencies where other teams or portfolios rely on their inputs, deliverables, or expertise\nCoordinate with teams to confirm that dependency-related activities and additional work are included in planning where required\nFacilitate discussions between portfolios to clarify timelines, ownership, and delivery expectations for dependent work\nSupport alignment during TI Planning by ensuring that teams understand when dependent deliverables are expected to be completed\nMonitor and escalate any unresolved risks or dependencies that may impact delivery commitments for the upcoming term",
      relatedArtefact: null
    },
    {
      id: "inspect-adapt-demo",
      name: "Inspect & Adapt Demo",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "IAD",
      sprints: ["sprint-6-ia"],
      description: "In this ceremony full term progress is demonstrated and measured against goals. This is also the time when the team reviews any metrics they had agreed to track for the term. It is also a retrospective and problem-solving workshop for teams to reflect on their ways of working with a view to embracing a culture of continuous improvement.",
      outcome: "Full-term progress is reviewed against goals, metrics are assessed, and teams reflect and problem-solve to drive continuous improvement.",
      whoAttends: "Change Portfolio Chair, Change Portfolio Product Management, Relevant Platform and Product team representatives, LPG Rep for Change Portfolio, All teams within the Change Portfolio",
      keyResponsibilities: "Facilitate the session and ensure all relevant attendees are invited",
      relatedArtefact: "inspect-adapt-prep"
    },
    {
      id: "inspect-adapt-prep",
      name: "Inspect & Adapt Prep",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "IAD",
      sprints: ["sprint-6-ia"],
      description: "A consolidated summary of progress, metrics, insights, and key improvement areas captured from the term review, used to inform decision-making and drive continuous improvement actions.",
      outcome: "The Portfolio Inspect & Adapt slides are updated with portfolio progress against term outcomes, including metrics and key insights.",
      whoAttends: "Change Portfolio Chair, Change Portfolio Product Management, Relevant Platform and Product team representatives, LPG Rep for Change Portfolio, All teams within the Change Portfolio",
      keyResponsibilities: "",
      relatedMeeting: "inspect-adapt-demo"
    },
    {
      id: "portfolio-vision",
      name: "Portfolio Vision",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "PV",
      sprints: ["sprint-6-ia"],
      description: "A session to define a clear, shared future vision for the portfolio that aligns strategy, guides investment decisions, and motivates teams.",
      outcome: "A well-defined and aligned portfolio vision that provides strategic direction and clarity for teams and stakeholders.",
      whoAttends: "Change Portfolio Chair, Change Portfolio Product Management, Relevant Platform and Product team representatives, LPG Rep for Change Portfolio, All teams within the Change Portfolio",
      keyResponsibilities: "Create a new vision slides\nReview the slide format with the Portfolio Leadership team\nMake sure slides are shared with their teams ahead of the session to allow enough time for teams to update\nMake sure the content is provided by their teams and it aligns with the portfolio roadmap",
      relatedArtefact: "portfolio-vision-prep"
    },
    {
      id: "portfolio-vision-prep",
      name: "Portfolio Vision Prep",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "PV",
      sprints: ["sprint-6-ia"],
      description: "A set of prepared slides capturing strategic inputs, priorities, and insights that the portfolio updates ahead of the session to support defining the future vision.",
      outcome: "Portfolio Vision slides are updated with aligned strategic direction, key priorities, and a clearly articulated future state for the portfolio.",
      whoAttends: "Change Portfolio Chair, Change Portfolio Product Management, Relevant Platform and Product team representatives, LPG Rep for Change Portfolio, All teams within the Change Portfolio",
      keyResponsibilities: "Create a new vision slides\nReview the slide format with the Portfolio Leadership team\nMake sure slides are shared with their teams ahead of the session to allow enough time for teams to update\nMake sure the content is provided by their teams and it aligns with the portfolio roadmap",
      relatedMeeting: "portfolio-vision"
    },
    {
      id: "cross-portfolio-vision",
      name: "Cross Portfolio Vision (Vision of Visions)",
      category: "ti-planning",
      type: "meeting",
      activityGroup: "VoV",
      sprints: ["sprint-6-ia"],
      description: "Align the portfolios around a shared strategic vision, identify common goals, dependencies, potential resource constraints and establish a coordinated direction for delivering impactful transformation in the term.",
      outcome: "Clear cross-portfolio visibility and alignment going into TI planning.",
      whoAttends: "CIO, Director of Delivery, Portfolio Leadership Groups (PDMs, Portfolio Owners, Portfolio Leads, Portfolio BAs, Portfolio Architects) and Capability Leads, Head of LPG",
      keyResponsibilities: "Identify and list all cross-portfolio dependencies.",
      relatedArtefact: "cross-portfolio-vision-prep"
    },
    {
      id: "cross-portfolio-vision-prep",
      name: "Cross Portfolio Vision Prep (Vision of Visions Prep)",
      category: "ti-planning",
      type: "artefact",
      activityGroup: "VoV",
      sprints: ["sprint-6-ia"],
      description: "A set of updated Vision of Vision slides and a dependency tracking spreadsheet capturing cross-portfolio dependencies, priorities, and alignment inputs ahead of the session.",
      outcome: "Updated Vision of Vision slides and dependency overview, providing clear cross-portfolio visibility, aligned priorities, and readiness for coordinated TI planning.",
      whoAttends: "Change Portfolio Delivery Manager",
      keyResponsibilities: "",
      relatedMeeting: "cross-portfolio-vision"
    },

    // ========== DELIVERY ==========
    {
      id: "extended-delivery-sync",
      name: "Extended Delivery Sync",
      category: "delivery",
      type: "meeting",
      activityGroup: "EDS",
      sprints: ["sprint-1", "sprint-2", "sprint-3", "sprint-4", "sprint-5", "sprint-6-ia"],
      description: "Sprintly playback of progress against agreed termly Outcomes to Director of Delivery.",
      outcome: "The Director of Delivery and PDMs share visibility of progress against termly outcomes, addressing risks, dependencies, and any required interventions.",
      whoAttends: "Director of Delivery, PDMs, Head of Portfolio Operations",
      keyResponsibilities: "",
      relatedArtefact: "extended-delivery-report"
    },
    {
      id: "extended-delivery-report",
      name: "Extended Delivery Report",
      category: "delivery",
      type: "artefact",
      activityGroup: "EDS",
      sprints: ["sprint-1", "sprint-2", "sprint-3", "sprint-4", "sprint-5", "sprint-6-ia"],
      description: "Updated Extended Delivery slides capturing progress against termly outcomes, key risks, dependencies, and required interventions.",
      outcome: "Clear, shared visibility of progress against termly outcomes, with risks, dependencies, and interventions identified and aligned between the Director of Delivery and PDMs.",
      whoAttends: "Change Portfolio Delivery Manager",
      keyResponsibilities: "",
      relatedMeeting: "extended-delivery-sync"
    },
    {
      id: "delivery-health-portfolio-review",
      name: "Delivery Health & Portfolio Review",
      category: "delivery",
      type: "meeting",
      activityGroup: "DHPR",
      sprints: ["sprint-2", "sprint-4"],
      description: "Review updates and RAG against committed Outcomes, highlight outstanding or emerging risks and issues and review Financial position for each Change Portfolio.",
      outcome: "Provides clear visibility and opportunity for scrutiny of delivery confidence, dependencies, risks, and financial position across portfolios, enabling escalation of issues and risks, and informed decisions and resolutions.",
      whoAttends: "CIO LT, Capability Leads, PDMs, Head of LPG",
      keyResponsibilities: "",
      relatedArtefact: "delivery-health-prep"
    },
    {
      id: "delivery-health-prep",
      name: "Delivery Health & Portfolio Prep",
      category: "delivery",
      type: "artefact",
      activityGroup: "DHPR",
      sprints: ["sprint-2", "sprint-4"],
      description: "Updated Delivery Health slides capturing RAG status against committed outcomes, along with key risks, issues, dependencies, and financial position for each portfolio.",
      outcome: "Clear visibility and scrutiny of delivery confidence, dependencies, risks, and financial position across portfolios, enabling escalation and informed decision-making.",
      whoAttends: "Change Portfolio Delivery Manager",
      keyResponsibilities: "",
      relatedMeeting: "delivery-health-portfolio-review"
    },
    {
      id: "resource-meeting",
      name: "Resource Meeting ITPPD (Delivery and Dev & Test)",
      category: "delivery",
      type: "meeting",
      activityGroup: "RM",
      sprints: ["sprint-2", "sprint-4"],
      description: "This is a monthly meeting held with the PDMs to review assignments, vacancies, subcontractor contract dates, and budgets. PDMs should use this as an opportunity to discuss resource changes, and highlight opportunities for cross-portfolio development for both IT Delivery and Development and Test staff.",
      outcome: "Clear and aligned view of resource allocation, capacity, and workforce risks, with actions agreed to optimise utilisation and support cross-portfolio development opportunities.",
      whoAttends: "ITPPD Director, Staff Operations Manager, Head of LPG, Portfolio Delivery Managers, Dev & Test Representatives",
      keyResponsibilities: "",
      relatedArtefact: null
    },
    {
      id: "jamboree",
      name: "Jamboree",
      category: "delivery",
      type: "meeting",
      activityGroup: "JAM",
      sprints: ["sprint-5"],
      description: "A quarterly collaborative event designed to share insights, facilitate engaging discussions, and strengthen connections across teams. This is an in-person event, and attendance is mandatory for all Delivery and LPG roles within ITPPD.",
      outcome: "Shared understanding and strengthened collaboration across teams, with key insights exchanged and connections reinforced to support effective delivery.",
      whoAttends: "ITTPD Director, Change Portfolio Delivery Manager, Agile Delivery Manager, IT Delivery Support Officer, Lean Portfolio Group",
      keyResponsibilities: "Ensure that ADMs and Support Officers are aware of the event and attend as required",
      relatedArtefact: null
    },
    {
      id: "showcase-demo",
      name: "Showcase Demo",
      category: "delivery",
      type: "meeting",
      activityGroup: "SD",
      sprints: ["sprint-3", "sprint-4"],
      description: "To showcase progress and demonstrate delivered value across the digital change portfolios, enabling visibility, engagement, and shared learning.",
      outcome: "Stakeholders gain visibility of recent delivery achievements, provide feedback.",
      whoAttends: "Product and Platform Teams, Product and Platform Owners, Change Portfolio Leadership Teams, Lean Portfolio Group, Centre of Excellence, ISD Leadership, Relevant key stakeholders external to ISD",
      keyResponsibilities: "Identify and coordinate representation from their respective Change Portfolios for the Showcase Demo",
      relatedArtefact: "showcase-demo-agenda"
    },
    {
      id: "showcase-demo-agenda",
      name: "Showcase Demo Agenda",
      category: "delivery",
      type: "artefact",
      activityGroup: "SD",
      sprints: ["sprint-3", "sprint-4"],
      description: "The PDM to identify and coordinate representation from their respective Change Portfolios for the Showcase Demo.",
      outcome: "The Portfolio Showcase Demos are confirmed and added to the Showcase Demo Agenda.",
      whoAttends: "Product and Platform Teams, Product and Platform Owners, Change Portfolio Delivery Manager, Agile Delivery Manager",
      keyResponsibilities: "Identify and coordinate representation from their respective Change Portfolios for the Showcase Demo",
      relatedMeeting: "showcase-demo"
    },

    // ========== FINANCES ==========
    {
      id: "monthly-finance-review",
      name: "Monthly Finance LT Review Meeting",
      category: "finances",
      type: "meeting",
      activityGroup: "MFKT",
      sprints: ["sprint-1", "sprint-3", "sprint-5"],
      description: "A monthly meeting to review portfolio financial performance, including spend, forecasts, delivery progress, and financial risks against approved budgets.",
      outcome: "Clear alignment on portfolio financial position, with risks identified and actions agreed to maintain budget and delivery performance.",
      whoAttends: "Change Portfolio Owner, Change Portfolio Manager, Change Portfolio Lead",
      keyResponsibilities: "Reviewing monthly actual spend against forecast and budget with the Portfolio Leadership Team\nIdentifying variances, risks, and potential financial impacts\nDiscussing delivery delays or scope changes that may affect financial plans\nConfirming that future costs and resource requirements are reflected in forecasts\nAgreeing on any corrective actions or escalation items required",
      relatedArtefact: "monthly-finance-plans"
    },
    {
      id: "monthly-finance-plans",
      name: "Monthly Finance Plans",
      category: "finances",
      type: "artefact",
      activityGroup: "MFKT",
      sprints: ["sprint-1", "sprint-3", "sprint-5"],
      description: "A monthly update of portfolio financial plans with actual spend provided by the Lean Portfolio Group, reviewed by the PDM to validate forecasts and ensure alignment within allocated budgets.",
      outcome: "Accurate and aligned financial plans, with forecasts validated and managed within budget to support effective financial control and delivery.",
      whoAttends: "Change Portfolio Manager, Lean Portfolio Group Rep",
      keyResponsibilities: "Review the actual spend against the forecast and budget\nEnsure that ADMs and Product Owners review their forecasts and include all anticipated future costs\nEnsure that forecasts remain within the allocated budget",
      relatedMeeting: "monthly-finance-review"
    },

    // ========== LBCs & DDTC ==========
    {
      id: "ddtc-meeting",
      name: "Digital Delivery and Transformation Committee (DDTC) Meeting",
      category: "lbcs-ddtc",
      type: "meeting",
      activityGroup: "DDTC",
      sprints: ["sprint-6-ia"],
      description: "A quarterly governance meeting that maintains a single portfolio of digital investment, reviewing funding allocations, approving Lean Business Cases, and assessing portfolio risks and delivery progress across strategic change, change, enhancement, and maintenance LBCs.",
      outcome: "Approved investment decisions and Lean Business Cases, with clear alignment on priorities, risks, and progress against portfolio outcomes.",
      whoAttends: "Director of Information Services Division, ITTPD Director, Portfolio Owner",
      keyResponsibilities: "",
      relatedArtefact: "ddtc-artefact-prep"
    },
    {
      id: "ddtc-lbc-drafts",
      name: "DDTC LBC Drafts",
      category: "lbcs-ddtc",
      type: "artefact",
      activityGroup: "DDTC",
      sprints: ["sprint-2"],
      description: "The purpose of this quarterly activity is to ensure that all Lean Business Cases (LBCs) requiring approval from the Digital Delivery and Transformation Committee (DDTC) are prepared, reviewed, and approved through the appropriate governance process before being shared with DDTC members. Product Owners are responsible for drafting the LBCs, which must first be reviewed and approved by the Change Portfolio Governance Board.",
      outcome: "The LBC is drafted and ready to be reviewed and approved by the Change Portfolio Governance Board.",
      whoAttends: "Change Portfolio Manager, Change Portfolio Lead, Product and Platform Owner",
      keyResponsibilities: "Ensure that all required LBCs are drafted by the Product Owners within agreed timelines\nEnsure that each LBC is reviewed by the Portfolio Owner prior to governance submission\nCoordinate the review process with the Change Portfolio Governance Board\nEnsure that all LBCs receive Governance Board approval before distribution to DDTC members\nTrack progress, approvals, and any required actions or amendments prior to DDTC submission",
      relatedMeeting: "ddtc-meeting"
    },
    {
      id: "ddtc-lbc-capability-sign-off",
      name: "DDTC LBC Capability Sign Off",
      category: "lbcs-ddtc",
      type: "artefact",
      activityGroup: "DDTC",
      sprints: ["sprint-4"],
      description: "A quarterly activity to review, update, and secure capability sign-off for Lean Business Cases (LBCs) prior to submission to DDTC, supported by coordination where needed.",
      outcome: "All LBCs are reviewed, aligned, and formally signed off by relevant capabilities, ready for submission to DDTC for approval.",
      whoAttends: "Change Portfolio Manager, Change Portfolio Lead, Product and Platform Owner",
      keyResponsibilities: "Ensure that each LBC is shared with the relevant Capability representatives for review\nEnsure that all relevant sections of the LBC are reviewed and updated as required\nConfirm that Capability feedback and required amendments are incorporated into the final version\nEnsure that formal Capability sign-off is obtained prior to DDTC submission\nTrack the progress of reviews and follow up on outstanding actions or approvals to meet agreed timelines",
      relatedMeeting: "ddtc-meeting"
    },
    {
      id: "ddtc-artefact-prep",
      name: "DDTC Artefact Prep",
      category: "lbcs-ddtc",
      type: "artefact",
      activityGroup: "DDTC",
      sprints: ["sprint-4", "sprint-5"],
      description: "A quarterly activity to prepare, review, and share key DDTC artefacts (including LBC cover slides and portfolio performance slides) in advance, ensuring effective governance and informed decision-making.",
      outcome: "Complete and high-quality DDTC artefacts shared in advance, enabling efficient review and informed investment and governance decisions.",
      whoAttends: "Change Portfolio Manager, Change Portfolio Lead, Product and Platform Owner",
      keyResponsibilities: "Ensure that all submitted LBCs have an up-to-date and completed LBC Cover Slide\nEnsure that all required DDTC artefacts are prepared in line with agreed standards and timelines\nEnsure that the Portfolio Performance slides are updated with the latest portfolio status, financials, risks, and delivery information\nCoordinate the review and quality check of all presentation materials before distribution\nEnsure that all DDTC artefacts are shared with DDTC members ahead of the meeting within the agreed submission timelines",
      relatedMeeting: "ddtc-meeting"
    },
    {
      id: "pre-ddtc-meeting",
      name: "Pre DDTC Meeting (Risks)",
      category: "lbcs-ddtc",
      type: "meeting",
      activityGroup: "DDTCR",
      sprints: ["sprint-5"],
      description: "A preparatory session to review portfolio delivery confidence (RAG status), key cross-portfolio risks and dependencies, and address any critical issues ahead of the DDTC meeting.",
      outcome: "Aligned view of delivery confidence, risks, and dependencies, with key issues clarified and ready for escalation and discussion at DDTC.",
      whoAttends: "Director of Information Services Division (CIO), ITTPD Director, Portfolio Owner",
      keyResponsibilities: "",
      relatedArtefact: "ddtc-pre-workshop-prep"
    },
    {
      id: "ddtc-pre-workshop-prep",
      name: "DDTC Pre Workshop Prep",
      category: "lbcs-ddtc",
      type: "artefact",
      activityGroup: "DDTCR",
      sprints: ["sprint-5"],
      description: "Preparation of DDTC pre-workshop slides, updated by the PDM to reflect delivery confidence, key risks, dependencies, and discussion points ahead of the session.",
      outcome: "Up-to-date pre-workshop slides that clearly capture delivery confidence, risks, and dependencies, enabling focused and effective discussion during the session.",
      whoAttends: "Change Portfolio Manager, Change Portfolio Lead",
      keyResponsibilities: "",
      relatedMeeting: "pre-ddtc-meeting"
    }
  ]
};
